### ISSUE TITLE
[Rejection] Deprecation notice si on ne met pas de "exchange"

### ISSUE THREAD

**Issue by clemzarch** [php-etl/satellite#125]
Si l'option `exchange` n'est pas renseignée, par exemple:
```
              rejection:
                destinations:
                  - rabbitmq:
                      host: '@=env("RABBITMQ_HOST")'
                      port: '@=env("RABBITMQ_PORT")'
                      user: '@=env("RABBITMQ_USER")'
                      password: '@=env("RABBITMQ_PASSWORD")'
                      vhost: '@=env("RABBITMQ_VHOST")'
                      topic: products
```

l'execution affiche:
```
Deprecated: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /Users/clementzarch/project/build/vendor/bunny/bunny/src/Bunny/ClientMethods.php on line 1780

Deprecated: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /Users/clementzarch/project/build/vendor/bunny/bunny/src/Bunny/ClientMethods.php on line 1784
```
parce que strlen prend forcément une string
![image](https://github.com/php-etl/satellite/assets/28787740/7bf343d7-4429-468c-af69-dbae2529ed73)
