### ISSUE TITLE
Dependency injection for states

### ISSUE THREAD

**Issue by sebprt** [php-etl/satellite#33]
Add the possibility to define a state at the same config level as the steps that can be used as a service in any step

```yaml
pipeline:
  state:
	destinations: # ...
  steps: 
	- csv: 
		extractor:
      state:
	    destinations: 
		  - rabbitmq: # ...
		  - "@state.general"
```
