### ISSUE TITLE
Add the Workflow runtime

### ISSUE THREAD

**Issue by gplanchat** [php-etl/satellite#5]
Add the Workflow runtime, a workflow is a combination of several pipelines and actions.

Workflows declarations should look like:

```yaml
satellite:
  workflow:
    name: 'Lorem ipsum dolor'
    jobs:
    - name: 'Sit amet consecutir'
      pipeline:
        steps:
        - akeneo:
// ...
    - name: 'Nulla rutrum non purus at iaculis'
      pipeline:
        steps:
        - akeneo:
// ...
```
