### ISSUE TITLE
batch size after first occurence

### ISSUE THREAD

**Issue by DnD-Magnum** [php-etl/satellite#67]
Hello, 

When you use batch tranformer option in your pipeline configuration, you have an error on the batch size after the first occurence.
For exemple , with the batch size to 100 : 
```
-
  batch:
    merge:
      size: 100
```

Your first batch will contain 100 items, but the other batches will contain 101 items. 

Geoffrey
